version: 2.1

executors:
  my-executor:
    docker: 
      - image: cimg/base:stable
jobs:
  say-hello:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  say-hi:
    executor: my-executor
    steps:
      - checkout
      - run: echo "Hi there"
      
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-hi
